import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useForm } from "react-hook-form";


export default function Home() {
  const { register, handleSubmit, watch,setError, formState: { errors } } = useForm();
  const { onChange:onPasswordChange, ...rest } = register("username");
  const onSubmit = data => console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>React Hook form test - Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Form Test
        </h1>
        <div style={{ display: "flex" }}>
          <form style={{ width:"50%", display: "flex", flexDirection: "column", gap: "16px", marginRight: "24px", padding: "24px" }} onSubmit={handleSubmit(onSubmit)}>
            <label for="name"/>
            <input {...register("name")} />
            <input onChange={(e)=>{
                setError("password", {
                  type: "manual",
                  message: "Dont Forget Your Password is visible!",
                })
                onPasswordChange(e);
              }
            } />
            {errors.password && <span>Password is visible man</span>}
            <button type="submit">Submit</button>
          </form>
          <div style={{width:"50%", padding:24}}>
            <h3>Outputs</h3>
            <p>Name :{watch("name")} </p>
  
          </div>
        </div>
      </main>
    </div>
  )
}
